databases:
  - name: osakacafegram_development
    databaseName: osakacafegram_development
    user: osakacafegram_development_user
    region: Oregon

services:
  - type: web
    name: osakacafegram_development
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    preDeployCommand: ./bin/rails db:migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: osakacafegram_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: RAILS_ENV
        value: production